export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR =  'AJAX_CALL_ERROR';
export const LOAD_CUSTOMERS_SUCCESS ='LOAD_CUSTOMERS_SUCCESS';
export const LOAD_HOTELS_SUCCESS ='LOAD_HOTELS_SUCCESS';
export const CREATE_CUSTOMER_SUCCESS ='CREATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_SUCCESS ='UPDATE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_SUCCESS ='DELETE_CUSTOMER_SUCCESS';
